name: "build"
on: [push, pull_request]
env:
  TRIVY_VERSION: 0.25.0
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Check out code
        uses: actions/checkout@v1

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v${{ env.TRIVY_VERSION }}

      - name: Test
        run: bats -r .